sudo: false
language: node_js
node_js: '8'

cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn run build:prod

deploy:
  - provider: script
    script: ./scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master

env:
  global:
    secure: sdtwGsfNEExRJmS3eYsx1aCIHzEkyCPlCUeDJFMYD+HYAtli0FxaPdWLS+zlUhNiWiSFoLOx1HbS/wK9xEo4EwsYvOePqu4ruO3ohvet40UmAGNIAjXjykaKZnJOggycooypmcD2hHrL7PwAud5EpatNUe8nmZM3xxjltyf935akAYXyE+/1o3oe8vVnwo1zZk+2rKJ4Rj6R3lO20vTkGKr+MMkIqWx9y6FSC03ufZgweYBB10lO7tgb2JxoxjptHxWjW73EXbKJTvPTuzlwVWUjzpBfLPL1BB2K+W9aWCQ3jHeV5BCmqqu2jXhugZZkP8gp47E/Pw54hXYdjePeGsGubrZu6ODXAyL0C6FvdbM+Nkln6xZi12Z7N+/jLRGbfhNY9V1foMFdhP045C47Kf85LhAq/i2HhhnwSrlE2i6WVMQ+gKv2L8avz8WbaReR9Z1Eb5bZaVZDBC8ikQPoFK9X89E5Ka4T2NcfgMsGHXOxc1un1+XK0lBYyiiA97Lo57Aw8b0RfVSurvjeR1uqQFvRcLFzmTCQEMqp1NBKA4oOYbS52pW8+SDf8uT3oEnaDAN7ecImte15GNnAw/wxPuH/To4xqotEe/OxYOH3LZNPPXLegozh7+g9+namT//4+quJTU16i9cd2yqQDR1QQVTz1iL/UK9PxX9jzBGxHyE=
